platform :ios, '7.0'

target 'ActorClient' do

# ABPhoneField dependency
pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'
#pod 'SHSPhoneComponent'

# Model
pod 'J2ObjC', :git => 'https://github.com/actorapp/j2objc'
pod 'RegexKitLite', :inhibit_warnings => true
pod 'CocoaAsyncSocket'
pod 'Objective-LevelDB', :inhibit_warnings => true
pod 'MagicalRecord', :inhibit_warnings => true

end

target 'ActorClientTests' do

end

