platform :ios, '7.0'

target 'ActorClient' do

# ABPhoneField dependency
pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'
#pod 'SHSPhoneComponent'

end

target 'ActorClientTests' do

end

